#influx command to create all access token - > then write to env variable.
#influx auth create --org my-org --all-access
#
# 
name: CI
on:
  pull_request:
  push:
    branches: [main]
    tags: ['*']
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.8'
          - '1' # automatically expands to the latest stable 1.x release of Julia
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
        include:
          - os: windows-latest
            version: '1'
            arch: x86
    steps:    
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup InfluxDB
        #uses: influxdata/influxdb-action@v3
        uses: kafisatz/influxdb-action@v4
        with:
          influxdb_version: latest
          influxdb_org: ${{ secrets.INFLUXDB_ORG }}
          influxdb_user: ${{ secrets.INFLUXDB_USER }}
          influxdb_password: ${{ secrets.INFLUXDB_PASSWORD }}
          influxdb_bucket: dummy_bucket      
          influxdb_token: ${{ secrets.INFLUXDB_TOKEN }}
      - uses: influxdata/influxdb-action@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          JULIA_NUM_THREADS: 4          
          INFLUXDB_ORG: ${{ secrets.INFLUXDB_ORG }}
          INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
          INFLUXDB_PASSWORD: ${{ secrets.INFLUXDB_PASSWORD }}
          INFLUXDB_TOKEN: ${{ secrets.INFLUXDB_TOKEN }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
  